### ISSUE TITLE
Optionally show the Document Outline

### ISSUE THREAD

**Issue by matthew-ia** [lorenzodelijser/paper#3]
By default, the Document Outline view is hidden even if it is set to show within the Docs menu: `View > Show Document Outline`. I assume this is intentional; if it is, then it might be neat to add a settings panel that allows you to show/hide the Document Outline when you're in "Focus" mode.

P.S. Cool extension!

**Comment by lorenzodelijser** [comment]
Thank you for the feedback @matthew-ia. I've updated the code to show the Document Outline view by default in version
1.0.2. This fix also has been pushed to the [Chrome Web Store](https://chrome.google.com/webstore/detail/focus-for-google-docs/ehogfddbkbeoadolmjppehadlpkbmfkn).


https://user-images.githubusercontent.com/29688706/105759984-6d8ed900-5f51-11eb-9c0e-487fdc5a40ca.mov
